image:
  pullPolicy: IfNotPresent
  repository: us-central1-docker.pkg.dev/clabs-gnosis-safe/images/safe-transaction-service
  tag: 61ee03ee2f712941c2b319d1cf2240c414a2177c

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    test: test
  enabled: true
  hosts:
  - host: transaction-service.celo-safe.io
    paths:
    - path: /
  tls:
  - hosts:
    - transaction-service.celo-safe.io
    secretName: transaction-service-tls

redis:
  replica:
    replicaCount: 1

global:
  postgresql:
    postgresqlDatabase: database
    postgresqlPassword: test
    servicePort: 5432
  redis:
    password: test
