apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safe-transaction-service-helm.fullname" . }}
  labels:
    {{- include "safe-transaction-service-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "safe-transaction-service-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "safe-transaction-service-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "safe-transaction-service-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: indexer-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker/web/celery/worker/run.sh"]
          env:
            - name: RUN_MIGRATIONS
              value: "1"
            - name: WORKER_QUEUES
              value: "default,indexing"
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}
            - name: ETHEREUM_NODE_URL
              value: {{ .Values.env.ethereumNodeUrl }}
            - name: ETH_L2_NETWORK
              value: "1"
            - name: REDIS_URL
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.env.djangoSecretKey }}"
            - name: CELERY_BROKER_URL
              value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: contracts-tokens-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker/web/celery/worker/run.sh"]
          env:
            - name: WORKER_QUEUES
              value: "contracts,tokens"
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}
            - name: ETHEREUM_NODE_URL
              value: {{ .Values.env.ethereumNodeUrl }}
            - name: ETH_L2_NETWORK
              value: "1"
            - name: REDIS_URL
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.env.djangoSecretKey }}"
            - name: CELERY_BROKER_URL
              value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: notifications-webhooks-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker/web/celery/worker/run.sh"]
          env:
            - name: WORKER_QUEUES
              value: "notifications,tokens"
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}
            - name: ETHEREUM_NODE_URL
              value: {{ .Values.env.ethereumNodeUrl }}
            - name: ETH_L2_NETWORK
              value: "1"
            - name: REDIS_URL
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.env.djangoSecretKey }}"
            - name: CELERY_BROKER_URL
              value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker/web/celery/scheduler/run.sh"]
          env:
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}
            - name: ETHEREUM_NODE_URL
              value: {{ .Values.env.ethereumNodeUrl }}
            - name: ETH_L2_NETWORK
              value: "1"
            - name: REDIS_URL
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.env.djangoSecretKey }}"
            - name: CELERY_BROKER_URL
              value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: flower
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker/web/celery/flower/run.sh"]
          env:
            - name: WORKER_QUEUES
              value: "notifications,tokens"
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}
            - name: ETHEREUM_NODE_URL
              value: {{ .Values.env.ethereumNodeUrl }}
            - name: ETH_L2_NETWORK
              value: "1"
            - name: REDIS_URL
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.env.djangoSecretKey }}"
            - name: CELERY_BROKER_URL
              value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: flower
              containerPort: 5555
              protocol: TCP
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker/web/run_web.sh"]
          env:
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.global.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}
            - name: ETHEREUM_NODE_URL
              value: {{ .Values.env.ethereumNodeUrl }}
            - name: ETH_L2_NETWORK
              value: "1"
            - name: REDIS_URL
              value: redis://:{{ .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379/0
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.local
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.env.djangoSecretKey }}"
            - name: CELERY_BROKER_URL
              value: amqp://user:{{ .Values.rabbitmq.auth.password }}@{{ .Release.Name }}-rabbitmq/
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
