apiVersion: v1
kind: Service
metadata:
  name: {{ include "safe-transaction-service-helm.fullname" . }}
  labels:
    {{- include "safe-transaction-service-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portHttp }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portFlower }}
      targetPort: flower
      protocol: TCP
      name: flower
  selector:
    {{- include "safe-transaction-service-helm.selectorLabels" . | nindent 4 }}
