apiVersion: v1
kind: Service
metadata:
  name: web-{{ include "safe-transaction-service-helm.fullname" . }}
  labels:
    {{- include "safe-transaction-service-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "safe-transaction-service-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
