# Generated by Django 4.1.3 on 2022-11-25 15:41

from django.db import migrations
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0067_auto_20220705_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigtransaction',
            name='gas_price',
            field=gnosis.eth.django.models.Uint256Field(null=True),
        ),
    ]
