# Generated by Django 4.1.3 on 2022-11-25 15:43

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0068_alter_multisigtransaction_gas_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethereumtx",
            name="gas_price",
            field=gnosis.eth.django.models.Uint256Field(null=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="gas_price",
            field=gnosis.eth.django.models.Uint256Field(default=1),
            preserve_default=False,
        ),
    ]
